# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: M0Oi2kf3Wq6+CvjZXnoyeJ5ckgVI9MPi4XBkI+krftBJ5/wtdAsX6D4inavqeytoE/6hxMFcpuW8GEGE3V3klcPqTufyxQXrOQMO+zY40Pd9ByUMb2tZFdOZopCXODh6Ks279GeoIRYKRDtYd+yFw0/L7zkHq6d4hvEG3HVr9mj9uipNwHTQNFw/AcWCNYZwMYZtJT/QRF/fKAP0f9GarfkcbD0RXdJ/4NxMduuFxA7XLPwAEGEIJoExQiuEWczhzVtNEIway7JnUdvU8XiG32Z/aAXHQbCemvTwqio6o7u5TwZlqmTqqbg4cXOIwdKSHRqH1GlwQY9JaXWa3kcpmb0zmUQicO+N7gYzOOYMk/mjyRZq72EKEeu3PtvsgcO47/FxeWWU6liBnPCWjIpumgEpfpGQjmLzDOb/eEgfaBAUi5U3P0hlAq6lqf/OGfe1NnQAHNnETXt9Z315aFMu9hC7+Ah2YkdIaf/PSO17niS3lB+64Q3PdVqiK0S0+f4IenJEVsl9+yKppn1z4I0LK44miisP/0RfNlO8M9HlU9k46umj8kmhzaeyaTAYczvXSEzvELe1j3CT8r79p/Ka1Un7YNoCIzswXn/VoogSud0NICt2biJpvhXqkv6VQrzXrtOSTy0o+s5a2jnxnXvad1xm9D6qdRCJ1I90djJQ+Iw=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-ceph
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: M0Oi2kf3Wq6+CvjZXnoyeJ5ckgVI9MPi4XBkI+krftBJ5/wtdAsX6D4inavqeytoE/6hxMFcpuW8GEGE3V3klcPqTufyxQXrOQMO+zY40Pd9ByUMb2tZFdOZopCXODh6Ks279GeoIRYKRDtYd+yFw0/L7zkHq6d4hvEG3HVr9mj9uipNwHTQNFw/AcWCNYZwMYZtJT/QRF/fKAP0f9GarfkcbD0RXdJ/4NxMduuFxA7XLPwAEGEIJoExQiuEWczhzVtNEIway7JnUdvU8XiG32Z/aAXHQbCemvTwqio6o7u5TwZlqmTqqbg4cXOIwdKSHRqH1GlwQY9JaXWa3kcpmb0zmUQicO+N7gYzOOYMk/mjyRZq72EKEeu3PtvsgcO47/FxeWWU6liBnPCWjIpumgEpfpGQjmLzDOb/eEgfaBAUi5U3P0hlAq6lqf/OGfe1NnQAHNnETXt9Z315aFMu9hC7+Ah2YkdIaf/PSO17niS3lB+64Q3PdVqiK0S0+f4IenJEVsl9+yKppn1z4I0LK44miisP/0RfNlO8M9HlU9k46umj8kmhzaeyaTAYczvXSEzvELe1j3CT8r79p/Ka1Un7YNoCIzswXn/VoogSud0NICt2biJpvhXqkv6VQrzXrtOSTy0o+s5a2jnxnXvad1xm9D6qdRCJ1I90djJQ+Iw=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-ceph
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: ZPv463BbsSpl9lBEEzz5ibKLD9GDSLBhrAGiwTfs4nEeTlHKevzIWs9KY5LpICe1d3pkGqJ8DHROK5jxsq5mdciR7quS/BJHSmJieKuumtirCZw3zW1989sVTh5BbyzTvTc1SSxVja07/XRkQosBHV9QnAJNPk6kJgJrQsMCsJ2mAxPD6mzYujNTKmgtDOVq30aFSBzIZwJXnsBE1XmTOKRqpaKFD3m4Tsi2JmVOIRrUB0Zasd1V6abFDbVIkae56FMnnFKAqnvaJODc4XZ7o1C7ia/YuqSpWUo4+tycrZaUWZ2O+uXCIUNBUtpZh74QZJEM0YwHcu/viD30buc5RWd63sS2rZScDiZFMCgjcQB0SC7/Pf3sO2q0tGahTP0JVcIr4shZ4ndAawKoNXghSbVMxzvwR2bJaiAxJFb5pz+hG1Ay0Kl7tWPvfe2YG6THQi9GbOMnkm40DY4Eai7V9/eIVNjan2EFWgvgVJTbBLebQy13Fm5xYANk+egK7xxTeYnQxFZE7yil0JphGyPHYLdFSzETIuKgd453zhvvm6/qsxgG7y7tRQye9ntT36NrprINWgPVy0LOus/fhvIeeUAOr9ChWFSwmZcLIE42lnaUIvzN/y9TIsFUP6iHPrWLlZg1HTju1Ro4HFVfoHMzo4ADKpccP8FlIaMZV+j3eEg=
  file:
    - release/snap-plugin-collector-ceph_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-ceph
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
