package ceph

type metric struct {
	ns          string
	description string
	unit        string
}

var allMetrics = []metric{
	// MDS
	{ns: "/intel/storage/ceph/mds/*/mds/request", description: "Requests"},
	{ns: "/intel/storage/ceph/mds/*/mds/reply", description: "Replies"},
	{ns: "/intel/storage/ceph/mds/*/mds/reply_latency", description: "Reply latency"},
	{ns: "/intel/storage/ceph/mds/*/mds/forward", description: "Forwarding request"},
	{ns: "/intel/storage/ceph/mds/*/mds/dir_fetch", description: "Directory fetch"},
	{ns: "/intel/storage/ceph/mds/*/mds/dir_commit", description: "Directory commit"},
	{ns: "/intel/storage/ceph/mds/*/mds/dir_split", description: "Directory split"},
	{ns: "/intel/storage/ceph/mds/*/mds/inode_max", description: "Max inodes, cache size"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes", description: "Inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_top", description: "Inodes on top"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_bottom", description: "Inodes on bottom"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_pin_tail", description: "Inodes on pin tail"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_pinned", description: "Inodes pinned"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_expired", description: "Inodes expired"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_with_caps", description: "Inodes with capabilities"},
	{ns: "/intel/storage/ceph/mds/*/mds/caps", description: "Capabilities"},
	{ns: "/intel/storage/ceph/mds/*/mds/subtrees", description: "Subtrees"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse", description: "Traverses"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_hit", description: "Traverse hits"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_forward", description: "Traverse forwards"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_discover", description: "Traverse directory discovers"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_dir_fetch", description: "Traverse incomplete directory content fetchings"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_remote_ino", description: "Traverse remote dentries"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_lock", description: "Traverse locks"},
	{ns: "/intel/storage/ceph/mds/*/mds/load_cent", description: "Load per cent"},
	{ns: "/intel/storage/ceph/mds/*/mds/q", description: "Dispatch queue length"},
	{ns: "/intel/storage/ceph/mds/*/mds/exported", description: "Exports"},
	{ns: "/intel/storage/ceph/mds/*/mds/exported_inodes", description: "Exported inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds/imported", description: "Imports"},
	{ns: "/intel/storage/ceph/mds/*/mds/imported_inodes", description: "Imported inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_strays", description: "Stray dentries"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_strays_purging", description: "Stray dentries purging"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_strays_delayed", description: "Stray dentries delayed"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_purge_ops", description: "Purge operations"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_created", description: "Stray dentries created"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_purged", description: "Stray dentries purged"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_reintegrated", description: "Stray dentries reintegrated"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_migrated", description: "Stray dentries migrated"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_recovering_processing", description: "Files currently being recovered"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_recovering_enqueued", description: "Files waiting for recovery"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_recovering_prioritized", description: "Files waiting for recovery with elevated priority"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/recovery_started", description: "File recoveries started"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/recovery_completed", description: "File recoveries completed"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evadd", description: "Events submitted"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evex", description: "Total expired events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evtrm", description: "Trimmed events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/ev", description: "Events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evexg", description: "Expiring events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evexd", description: "Current expired events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segadd", description: "Segments added"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segex", description: "Total expired segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segtrm", description: "Trimmed segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/seg", description: "Segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segexg", description: "Expiring segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segexd", description: "Current expired segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/expos", description: "Journaler xpire position"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/wrpos", description: "Journaler  write position"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/rdpos", description: "Journaler  read position"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/jlat", description: "Journaler flush latency"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/ino", description: "Inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/ino+", description: "Inodes opened"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/ino-", description: "Inodes closed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dir", description: "Directories"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dir+", description: "Directories opened"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dir-", description: "Directories closed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dn", description: "Dentries"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dn+", description: "Dentries opened"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dn-", description: "Dentries closed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/cap", description: "Capabilities"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/cap+", description: "Capabilities added"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/cap-", description: "Capabilities removed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/rss", description: "RSS"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/heap", description: "Heap size"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/malloc", description: "Malloc size"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/buf", description: "Buffer size"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/handle_client_request", description: "Client requests"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/handle_slave_request", description: "Slave requests"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/handle_client_session", description: "Client session messages"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/dispatch_client_request", description: "Client requests dispatched"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/dispatch_server_request", description: "Server requests dispatched"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_active", description: "Operations active"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_laggy", description: "Laggy operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_send", description: "Sent operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_send_bytes", description: "Sent data"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_resend", description: "Resent operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_ack", description: "Commit callbacks"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_commit", description: "Operation commits"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op", description: "Operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_r", description: "Read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_w", description: "Write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_rmw", description: "Read-modify-write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_pg", description: "PG operation"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_stat", description: "Stat operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_create", description: "Create object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_read", description: "Read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_write", description: "Write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_writefull", description: "Write full object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_append", description: "Append operation"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_zero", description: "Set object to zero operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_truncate", description: "Truncate object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_delete", description: "Delete object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_mapext", description: "Map extent operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_sparse_read", description: "Sparse read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_clonerange", description: "Clone range operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_getxattr", description: "Get xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_setxattr", description: "Set xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_cmpxattr", description: "Xattr comparison operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_rmxattr", description: "Remove xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_resetxattrs", description: "Reset xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_tmap_up", description: "TMAP update operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_tmap_put", description: "TMAP put operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_tmap_get", description: "TMAP get operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_call", description: "Call (execute) operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_watch", description: "Watch by object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_notify", description: "Notify about object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_src_cmpxattr", description: "Extended attribute comparison in multi operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_pgls", description: ""},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_pgls_filter", description: ""},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_other", description: "Other operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_active", description: "Active lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_send", description: "Sent lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_resend", description: "Resent lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_ping", description: "Sent pings to lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolop_active", description: "Active pool operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolop_send", description: "Sent pool operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolop_resend", description: "Resent pool operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolstat_active", description: "Active get pool stat operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolstat_send", description: "Pool stat operations sent"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolstat_resend", description: "Resent pool stats"},
	{ns: "/intel/storage/ceph/mds/*/objecter/statfs_active", description: "Statfs operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/statfs_send", description: "Sent FS stats"},
	{ns: "/intel/storage/ceph/mds/*/objecter/statfs_resend", description: "Resent FS stats"},
	{ns: "/intel/storage/ceph/mds/*/objecter/command_active", description: "Active commands"},
	{ns: "/intel/storage/ceph/mds/*/objecter/command_send", description: "Sent commands"},
	{ns: "/intel/storage/ceph/mds/*/objecter/command_resend", description: "Resent commands"},
	{ns: "/intel/storage/ceph/mds/*/objecter/map_epoch", description: "OSD map epoch"},
	{ns: "/intel/storage/ceph/mds/*/objecter/map_full", description: "Full OSD maps received"},
	{ns: "/intel/storage/ceph/mds/*/objecter/map_inc", description: "Incremental OSD maps received"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_sessions", description: "Open sessions"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_session_open", description: "Sessions opened"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_session_close", description: "Sessions closed"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_laggy", description: "Laggy OSD sessions"},
	{ns: "/intel/storage/ceph/mds/*/objecter/omap_wr", description: "OSD OMAP write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/omap_rd", description: "OSD OMAP read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/omap_del", description: "OSD OMAP delete operations"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/wait", description: "Waiting latency"},

	// MON
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mon", description: "Monitors"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mon_quorum", description: "Monitors in quorum"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_osd", description: "OSDs"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_osd_up", description: "OSDs that are up"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_osd_in", description: "OSD in state \"in\" (they are in cluster)"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_epoch", description: "Current epoch of OSD map"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_bytes", description: "Total capacity of cluster"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_bytes_used", description: "Used space"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_bytes_avail", description: "Available space"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pool", description: "Pools"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg", description: "Placement groups"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg_active_clean", description: "Placement groups in active+clean state"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg_active", description: "Placement groups in active state"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg_peering", description: "Placement groups in peering state"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object", description: "Objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object_degraded", description: "Degraded (missing replicas) objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object_misplaced", description: "Misplaced (wrong location in the cluster) objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object_unfound", description: "Unfound objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_bytes", description: "Size of all objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mds_up", description: "MDSs that are up"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mds_in", description: "MDS in state \"in\" (they are in cluster)"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mds_failed", description: "Failed MDS"},
	{ns: "/intel/storage/ceph/mon/*/cluster/mds_epoch", description: "Current epoch of MDS map"},
	{ns: "/intel/storage/ceph/mon/*/finisher-monstore/queue_len", description: ""},
	{ns: "/intel/storage/ceph/mon/*/finisher-monstore/complete_latency", description: ""},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_transaction", description: "Transactions"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_get_latency", description: "Get Latency"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_submit_latency", description: "Submit Latency"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_submit_sync_latency", description: "Submit Sync Latency"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact", description: "Compactions"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact_range", description: "Compactions by range"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact_queue_merge", description: "Mergings of ranges in compaction queue"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact_queue_len", description: "Length of compaction queue"},
	{ns: "/intel/storage/ceph/mon/*/mon/num_sessions", description: "Open sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/session_add", description: "Created sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/session_rm", description: "Removed sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/session_trim", description: "Trimmed sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/num_elections", description: "Elections participated in"},
	{ns: "/intel/storage/ceph/mon/*/mon/election_call", description: "Elections started"},
	{ns: "/intel/storage/ceph/mon/*/mon/election_win", description: "Elections won"},
	{ns: "/intel/storage/ceph/mon/*/mon/election_lose", description: "Elections lost"},
	{ns: "/intel/storage/ceph/mon/*/paxos/start_leader", description: "Starts in leader role"},
	{ns: "/intel/storage/ceph/mon/*/paxos/start_peon", description: "Starts in peon role"},
	{ns: "/intel/storage/ceph/mon/*/paxos/restart", description: "Restarts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/refresh", description: "Refreshes"},
	{ns: "/intel/storage/ceph/mon/*/paxos/refresh_latency", description: "Refresh latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin", description: "Started and handled begins"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_keys", description: "Keys in transaction on begin"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_bytes", description: "Data in transaction on begin"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_latency", description: "Latency of begin operation"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit", description: "Commits"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_keys", description: "Keys in transaction on commit"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_bytes", description: "Data in transaction on commit"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_latency", description: "Commit latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect", description: "Peon collects"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_keys", description: "Keys in transaction on peon collect"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_bytes", description: "Data in transaction on peon collect"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_latency", description: "Peon collect latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_uncommitted", description: "Uncommitted values in started and handled collects"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_timeout", description: "Collect timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/accept_timeout", description: "Accept timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/lease_ack_timeout", description: "Lease acknowledgement timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/lease_timeout", description: "Lease timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state", description: "Store a shared state on disk"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_keys", description: "Keys in transaction in stored state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_bytes", description: "Data in transaction in stored state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_latency", description: "Storing state latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state", description: "Sharings of state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state_keys", description: "Keys in shared state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state_bytes", description: "Data in shared state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/new_pn", description: "New proposal number queries"},
	{ns: "/intel/storage/ceph/mon/*/paxos/new_pn_latency", description: "New proposal number getting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/wait", description: "Waiting latency"},

	// OSD
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/bytes_dirtied", description: "Dirty data"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/bytes_wb", description: "Written data"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/ios_dirtied", description: "Dirty operations"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/ios_wb", description: "Written operations"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/inodes_dirtied", description: "Entries waiting for write"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/inodes_wb", description: "Written entries"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_queue_ops", description: "Operations in journal queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_queue_bytes", description: "Size of journal queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_ops", description: "Total journal entries written"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_bytes", description: "Total operations size in journal"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_latency", description: "Average journal queue completing latency"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_wr", description: "Journal write IOs"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_wr_bytes", description: "Journal data written"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_full", description: "Journal writes while full"},
	{ns: "/intel/storage/ceph/osd/*/filestore/committing", description: "Is currently committing"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle", description: "Commit cycles"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle_interval", description: "Average interval between commits"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle_latency", description: "Average latency of commit"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_max_ops", description: "Max operations in writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_ops", description: "Operations in writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/ops", description: "Operations written to store"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_max_bytes", description: "Max data in writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_bytes", description: "Size of writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/bytes", description: "Data written to store"},
	{ns: "/intel/storage/ceph/osd/*/filestore/apply_latency", description: "Apply latency"},
	{ns: "/intel/storage/ceph/osd/*/filestore/queue_transaction_latency_avg", description: "Store operation queue latency"},
	{ns: "/intel/storage/ceph/osd/*/finisher-JournalObjectStore/queue_len", description: ""},
	{ns: "/intel/storage/ceph/osd/*/finisher-JournalObjectStore/complete_latency", description: ""},
	{ns: "/intel/storage/ceph/osd/*/finisher-filestore-apply-0/queue_len", description: ""},
	{ns: "/intel/storage/ceph/osd/*/finisher-filestore-apply-0/complete_latency", description: ""},
	{ns: "/intel/storage/ceph/osd/*/finisher-filestore-ondisk-0/queue_len", description: ""},
	{ns: "/intel/storage/ceph/osd/*/finisher-filestore-ondisk-0/complete_latency", description: ""},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_transaction", description: "Transactions"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_get_latency", description: "Get Latency"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_submit_latency", description: "Submit Latency"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_submit_sync_latency", description: "Submit Sync Latency"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact", description: "Compactions"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact_range", description: "Compactions by range"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact_queue_merge", description: "Mergings of ranges in compaction queue"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact_queue_len", description: "Length of compaction queue"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::completions_lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::finisher_lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::write_lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::writeq_lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::ApplyManager::apply_lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::ApplyManager::com_lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::SubmitManager::lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:.0/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:.1/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:.2/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:.3/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:.4/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:order:.0/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:order:.1/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:order:.2/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:order:.3/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-OSD:ShardedOpWQ:order:.4/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-WBThrottle::lock/wait", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_active", description: "Operations active"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_laggy", description: "Laggy operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_send", description: "Sent operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_send_bytes", description: "Sent data"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_resend", description: "Resent operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_ack", description: "Commit callbacks"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_commit", description: "Operation commits"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op", description: "Operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_r", description: "Read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_w", description: "Write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_rmw", description: "Read-modify-write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_pg", description: "PG operation"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_stat", description: "Stat operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_create", description: "Create object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_read", description: "Read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_write", description: "Write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_writefull", description: "Write full object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_append", description: "Append operation"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_zero", description: "Set object to zero operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_truncate", description: "Truncate object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_delete", description: "Delete object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_mapext", description: "Map extent operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_sparse_read", description: "Sparse read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_clonerange", description: "Clone range operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_getxattr", description: "Get xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_setxattr", description: "Set xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_cmpxattr", description: "Xattr comparison operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_rmxattr", description: "Remove xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_resetxattrs", description: "Reset xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_tmap_up", description: "TMAP update operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_tmap_put", description: "TMAP put operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_tmap_get", description: "TMAP get operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_call", description: "Call (execute) operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_watch", description: "Watch by object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_notify", description: "Notify about object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_src_cmpxattr", description: "Extended attribute comparison in multi operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_pgls", description: ""},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_pgls_filter", description: ""},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_other", description: "Other operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_active", description: "Active lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_send", description: "Sent lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_resend", description: "Resent lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_ping", description: "Sent pings to lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolop_active", description: "Active pool operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolop_send", description: "Sent pool operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolop_resend", description: "Resent pool operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolstat_active", description: "Active get pool stat operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolstat_send", description: "Pool stat operations sent"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolstat_resend", description: "Resent pool stats"},
	{ns: "/intel/storage/ceph/osd/*/objecter/statfs_active", description: "Statfs operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/statfs_send", description: "Sent FS stats"},
	{ns: "/intel/storage/ceph/osd/*/objecter/statfs_resend", description: "Resent FS stats"},
	{ns: "/intel/storage/ceph/osd/*/objecter/command_active", description: "Active commands"},
	{ns: "/intel/storage/ceph/osd/*/objecter/command_send", description: "Sent commands"},
	{ns: "/intel/storage/ceph/osd/*/objecter/command_resend", description: "Resent commands"},
	{ns: "/intel/storage/ceph/osd/*/objecter/map_epoch", description: "OSD map epoch"},
	{ns: "/intel/storage/ceph/osd/*/objecter/map_full", description: "Full OSD maps received"},
	{ns: "/intel/storage/ceph/osd/*/objecter/map_inc", description: "Incremental OSD maps received"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_sessions", description: "Open sessions"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_session_open", description: "Sessions opened"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_session_close", description: "Sessions closed"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_laggy", description: "Laggy OSD sessions"},
	{ns: "/intel/storage/ceph/osd/*/objecter/omap_wr", description: "OSD OMAP write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/omap_rd", description: "OSD OMAP read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/omap_del", description: "OSD OMAP delete operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_wip", description: "Replication operations currently being processed (primary)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op", description: "Client operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_in_bytes", description: "Client operations total write size"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_out_bytes", description: "Client operations total read size"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_latency", description: "Latency of client operations (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_process_latency", description: "Latency of client operations (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_prepare_latency", description: "Latency of client operations (excluding queue time and wait for finished)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r", description: "Client read operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_out_bytes", description: "Client data read"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_latency", description: "Latency of read operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_process_latency", description: "Latency of read operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_prepare_latency", description: "Latency of read operations (excluding queue time and wait for finished)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w", description: "Client write operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_in_bytes", description: "Client data written"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_rlat", description: "Client write operation readable/applied latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_latency", description: "Latency of write operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_process_latency", description: "Latency of write operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_prepare_latency", description: "Latency of write operations (excluding queue time and wait for finished)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw", description: "Client read-modify-write operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_in_bytes", description: "Client read-modify-write operations write in"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_out_bytes", description: "Client read-modify-write operations read out "},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_rlat", description: "Client read-modify-write operation readable/applied latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_latency", description: "Latency of read-modify-write operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_process_latency", description: "Latency of read-modify-write operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_prepare_latency", description: "Latency of read-modify-write operations (excluding queue time and wait for finished)"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop", description: "Suboperations"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_in_bytes", description: "Suboperations total size"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_latency", description: "Suboperations latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_w", description: "Replicated writes"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_w_in_bytes", description: "Replicated written data size"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_w_latency", description: "Replicated writes latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_pull", description: "Suboperations pull requests"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_pull_latency", description: "Suboperations pull latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_push", description: "Suboperations push messages"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_push_in_bytes", description: "Suboperations pushed size"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_push_latency", description: "Suboperations push latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/pull", description: "Pull requests sent"},
	{ns: "/intel/storage/ceph/osd/*/osd/push", description: "Push messages sent"},
	{ns: "/intel/storage/ceph/osd/*/osd/push_out_bytes", description: "Pushed size"},
	{ns: "/intel/storage/ceph/osd/*/osd/push_in", description: "Inbound push messages"},
	{ns: "/intel/storage/ceph/osd/*/osd/push_in_bytes", description: "Inbound pushed size"},
	{ns: "/intel/storage/ceph/osd/*/osd/recovery_ops", description: "Started recovery operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/loadavg", description: "CPU load"},
	{ns: "/intel/storage/ceph/osd/*/osd/buffer_bytes", description: "Total allocated buffer size"},
	{ns: "/intel/storage/ceph/osd/*/osd/history_alloc_Mbytes", description: ""},
	{ns: "/intel/storage/ceph/osd/*/osd/history_alloc_num", description: ""},
	{ns: "/intel/storage/ceph/osd/*/osd/cached_crc", description: "Total number getting crc from crc_cache"},
	{ns: "/intel/storage/ceph/osd/*/osd/cached_crc_adjusted", description: "Total number getting crc from crc_cache with adjusting"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg", description: "Placement groups"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg_primary", description: "Placement groups for which this osd is primary"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg_replica", description: "Placement groups for which this osd is replica"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg_stray", description: "Placement groups ready to be deleted from this osd"},
	{ns: "/intel/storage/ceph/osd/*/osd/heartbeat_to_peers", description: "Heartbeat (ping) peers we send to"},
	{ns: "/intel/storage/ceph/osd/*/osd/map_messages", description: "OSD map messages"},
	{ns: "/intel/storage/ceph/osd/*/osd/map_message_epochs", description: "OSD map epochs"},
	{ns: "/intel/storage/ceph/osd/*/osd/map_message_epoch_dups", description: "OSD map duplicates"},
	{ns: "/intel/storage/ceph/osd/*/osd/messages_delayed_for_map", description: "Operations waiting for OSD map"},
	{ns: "/intel/storage/ceph/osd/*/osd/stat_bytes", description: "OSD size"},
	{ns: "/intel/storage/ceph/osd/*/osd/stat_bytes_used", description: "Used space"},
	{ns: "/intel/storage/ceph/osd/*/osd/stat_bytes_avail", description: "Available space"},
	{ns: "/intel/storage/ceph/osd/*/osd/copyfrom", description: "Rados \"copy-from\" operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_promote", description: "Tier promotions"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_flush", description: "Tier flushes"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_flush_fail", description: "Failed tier flushes"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_try_flush", description: "Tier flush attempts"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_try_flush_fail", description: "Failed tier flush attempts"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_evict", description: "Tier evictions"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_whiteout", description: "Tier whiteouts"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_dirty", description: "Dirty tier flag set"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_clean", description: "Dirty tier flag cleaned"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_delay", description: "Tier delays (agent waiting)"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_proxy_read", description: "Tier proxy reads"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_proxy_write", description: "Tier proxy writes"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_wake", description: "Tiering agent wake up"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_skip", description: "Objects skipped by agent"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_flush", description: "Tiering agent flushes"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_evict", description: "Tiering agent evictions"},
	{ns: "/intel/storage/ceph/osd/*/osd/object_ctx_cache_hit", description: "Object context cache hits"},
	{ns: "/intel/storage/ceph/osd/*/osd/object_ctx_cache_total", description: "Object context cache lookups"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_cache_hit", description: ""},
	{ns: "/intel/storage/ceph/osd/*/osd/osd_tier_flush_lat", description: "Object flush latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/osd_tier_promote_lat", description: "Object promote latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/osd_tier_r_lat", description: "Object proxy read latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/initial_latency", description: "Initial recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/started_latency", description: "Started recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/reset_latency", description: "Reset recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/start_latency", description: "Start recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/primary_latency", description: "Primary recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/peering_latency", description: "Peering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/backfilling_latency", description: "Backfilling recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitremotebackfillreserved_latency", description: "Wait remote backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitlocalbackfillreserved_latency", description: "Wait local backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/notbackfilling_latency", description: "Notbackfilling recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repnotrecovering_latency", description: "Repnotrecovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repwaitrecoveryreserved_latency", description: "Rep wait recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repwaitbackfillreserved_latency", description: "Rep wait backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/reprecovering_latency", description: "RepRecovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/activating_latency", description: "Activating recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitlocalrecoveryreserved_latency", description: "Wait local recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitremoterecoveryreserved_latency", description: "Wait remote recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/recovering_latency", description: "Recovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/recovered_latency", description: "Recovered recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/clean_latency", description: "Clean recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/active_latency", description: "Active recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/replicaactive_latency", description: "Replicaactive recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/stray_latency", description: "Stray recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getinfo_latency", description: "Getinfo recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getlog_latency", description: "Getlog recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitactingchange_latency", description: "Waitactingchange recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/incomplete_latency", description: "Incomplete recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getmissing_latency", description: "Getmissing recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitupthru_latency", description: "Waitupthru recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/wait", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/wait", description: "Waiting latency"},
}
