package ceph

type metric struct {
	ns          string
	description string
	unit        string
}

var allMetrics = []metric{
	// MDS
	{ns: "/intel/storage/ceph/mds/*/mds/reques", description: "Requests"},
	{ns: "/intel/storage/ceph/mds/*/mds/repl", description: "Replies"},
	{ns: "/intel/storage/ceph/mds/*/mds/reply_latency/avgcoun", description: "Reply latency"},
	{ns: "/intel/storage/ceph/mds/*/mds/reply_latency/su", description: "Reply latency"},
	{ns: "/intel/storage/ceph/mds/*/mds/forwar", description: "Forwarding request"},
	{ns: "/intel/storage/ceph/mds/*/mds/dir_fetc", description: "Directory fetch"},
	{ns: "/intel/storage/ceph/mds/*/mds/dir_commi", description: "Directory commit"},
	{ns: "/intel/storage/ceph/mds/*/mds/dir_spli", description: "Directory split"},
	{ns: "/intel/storage/ceph/mds/*/mds/inode_ma", description: "Max inodes cache size"},
	{ns: "/intel/storage/ceph/mds/*/mds/inode", description: "Inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_to", description: "Inodes on top"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_botto", description: "Inodes on bottom"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_pin_tai", description: "Inodes on pin tail"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_pinne", description: "Inodes pinned"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_expire", description: "Inodes expired"},
	{ns: "/intel/storage/ceph/mds/*/mds/inodes_with_cap", description: "Inodes with capabilities"},
	{ns: "/intel/storage/ceph/mds/*/mds/cap", description: "Capabilities"},
	{ns: "/intel/storage/ceph/mds/*/mds/subtree", description: "Subtrees"},
	{ns: "/intel/storage/ceph/mds/*/mds/travers", description: "Traverses"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_hi", description: "Traverse hits"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_forwar", description: "Traverse forwards"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_discove", description: "Traverse directory discovers"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_dir_fetc", description: "Traverse incomplete directory content fetchings"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_remote_in", description: "Traverse remote dentries"},
	{ns: "/intel/storage/ceph/mds/*/mds/traverse_loc", description: "Traverse locks"},
	{ns: "/intel/storage/ceph/mds/*/mds/load_cen", description: "Load per cent"},
	{ns: "/intel/storage/ceph/mds/*/mds/", description: "Dispatch queue length"},
	{ns: "/intel/storage/ceph/mds/*/mds/exporte", description: "Exports"},
	{ns: "/intel/storage/ceph/mds/*/mds/exported_inode", description: "Exported inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds/importe", description: "Imports"},
	{ns: "/intel/storage/ceph/mds/*/mds/imported_inode", description: "Imported inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_stray", description: "Stray dentries"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_strays_purgin", description: "Stray dentries purging"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_strays_delaye", description: "Stray dentries delayed"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_purge_op", description: "Purge operations"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_create", description: "Stray dentries created"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_purge", description: "Stray dentries purged"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_reintegrate", description: "Stray dentries reintegrated"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/strays_migrate", description: "Stray dentries migrated"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_recovering_processin", description: "Files currently being recovered"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_recovering_enqueue", description: "Files waiting for recovery"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/num_recovering_prioritize", description: "Files waiting for recovery with elevated priority"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/recovery_starte", description: "File recoveries started"},
	{ns: "/intel/storage/ceph/mds/*/mds_cache/recovery_complete", description: "File recoveries completed"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evad", description: "Events submitted"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/eve", description: "Total expired events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evtr", description: "Trimmed events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/e", description: "Events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evex", description: "Expiring events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/evex", description: "Current expired events"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segad", description: "Segments added"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/sege", description: "Total expired segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segtr", description: "Trimmed segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/se", description: "Segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segex", description: "Expiring segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/segex", description: "Current expired segments"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/expo", description: "Journaler xpire position"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/wrpo", description: "Journaler  write position"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/rdpo", description: "Journaler  read position"},
	{ns: "/intel/storage/ceph/mds/*/mds_log/jla", description: "Journaler flush latency"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/in", description: "Inodes"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/ino", description: "Inodes opened"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/ino", description: "Inodes closed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/di", description: "Directories"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dir", description: "Directories opened"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dir", description: "Directories closed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/d", description: "Dentries"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dn", description: "Dentries opened"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/dn", description: "Dentries closed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/ca", description: "Capabilities"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/cap", description: "Capabilities added"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/cap", description: "Capabilities removed"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/rs", description: "RSS"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/hea", description: "Heap size"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/mallo", description: "Malloc size"},
	{ns: "/intel/storage/ceph/mds/*/mds_mem/bu", description: "Buffer size"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/handle_client_reques", description: "Client requests"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/handle_slave_reques", description: "Slave requests"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/handle_client_sessio", description: "Client session messages"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/dispatch_client_reques", description: "Client requests dispatched"},
	{ns: "/intel/storage/ceph/mds/*/mds_server/dispatch_server_reques", description: "Server requests dispatched"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_activ", description: "Operations active"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_lagg", description: "Laggy operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_sen", description: "Sent operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_send_byte", description: "Sent data"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_resen", description: "Resent operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_ac", description: "Commit callbacks"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_commi", description: "Operation commits"},
	{ns: "/intel/storage/ceph/mds/*/objecter/o", description: "Operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_", description: "Read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_", description: "Write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_rm", description: "Read-modify-write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/op_p", description: "PG operation"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_sta", description: "Stat operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_creat", description: "Create object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_rea", description: "Read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_writ", description: "Write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_writeful", description: "Write full object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_appen", description: "Append operation"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_zer", description: "Set object to zero operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_truncat", description: "Truncate object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_delet", description: "Delete object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_mapex", description: "Map extent operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_sparse_rea", description: "Sparse read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_clonerang", description: "Clone range operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_getxatt", description: "Get xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_setxatt", description: "Set xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_cmpxatt", description: "Xattr comparison operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_rmxatt", description: "Remove xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_resetxattr", description: "Reset xattr operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_tmap_u", description: "TMAP update operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_tmap_pu", description: "TMAP put operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_tmap_ge", description: "TMAP get operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_cal", description: "Call (execute) operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_watc", description: "Watch by object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_notif", description: "Notify about object operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_src_cmpxatt", description: "Extended attribute comparison in multi operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_pgl", description: "[No description available]"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_pgls_filte", description: "[No description available]"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osdop_othe", description: "Other operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_activ", description: "Active lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_sen", description: "Sent lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_resen", description: "Resent lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/linger_pin", description: "Sent pings to lingering operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolop_activ", description: "Active pool operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolop_sen", description: "Sent pool operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolop_resen", description: "Resent pool operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolstat_activ", description: "Active get pool stat operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolstat_sen", description: "Pool stat operations sent"},
	{ns: "/intel/storage/ceph/mds/*/objecter/poolstat_resen", description: "Resent pool stats"},
	{ns: "/intel/storage/ceph/mds/*/objecter/statfs_activ", description: "Statfs operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/statfs_sen", description: "Sent FS stats"},
	{ns: "/intel/storage/ceph/mds/*/objecter/statfs_resen", description: "Resent FS stats"},
	{ns: "/intel/storage/ceph/mds/*/objecter/command_activ", description: "Active commands"},
	{ns: "/intel/storage/ceph/mds/*/objecter/command_sen", description: "Sent commands"},
	{ns: "/intel/storage/ceph/mds/*/objecter/command_resen", description: "Resent commands"},
	{ns: "/intel/storage/ceph/mds/*/objecter/map_epoc", description: "OSD map epoch"},
	{ns: "/intel/storage/ceph/mds/*/objecter/map_ful", description: "Full OSD maps received"},
	{ns: "/intel/storage/ceph/mds/*/objecter/map_in", description: "Incremental OSD maps received"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_session", description: "Open sessions"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_session_ope", description: "Sessions opened"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_session_clos", description: "Sessions closed"},
	{ns: "/intel/storage/ceph/mds/*/objecter/osd_lagg", description: "Laggy OSD sessions"},
	{ns: "/intel/storage/ceph/mds/*/objecter/omap_w", description: "OSD OMAP write operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/omap_r", description: "OSD OMAP read operations"},
	{ns: "/intel/storage/ceph/mds/*/objecter/omap_de", description: "OSD OMAP delete operations"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/va", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/ma", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/ge", description: "Gets"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/get_su", description: "Got data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/get_or_fail_fai", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/get_or_fail_succes", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/tak", description: "Takes"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/take_su", description: "Taken data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/pu", description: "Puts"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/put_su", description: "Put data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/wait/avgcoun", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mds/*/throttle-msgr_dispatch_throttler-mds/wait/su", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/va", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/ma", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/ge", description: "Gets"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/get_su", description: "Got data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/get_or_fail_fai", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/get_or_fail_succes", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/tak", description: "Takes"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/take_su", description: "Taken data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/pu", description: "Puts"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/put_su", description: "Put data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/wait/avgcoun", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_bytes/wait/su", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/va", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/ma", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/ge", description: "Gets"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/get_su", description: "Got data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/get_or_fail_fai", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/get_or_fail_succes", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/tak", description: "Takes"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/take_su", description: "Taken data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/pu", description: "Puts"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/put_su", description: "Put data"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/wait/avgcoun", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mds/*/throttle-objecter_ops/wait/su", description: "Waiting latency"},

	// MON
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mon", description: "Monitors"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mon_quorum", description: "Monitors in quorum"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_osd", description: "OSDs"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_osd_up", description: "OSDs that are up"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_osd_in", description: "OSD in state in (they are in cluster)"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_epoch", description: "Current epoch of OSD map"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_bytes", description: "Total capacity of cluster"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_bytes_used", description: "Used space"},
	{ns: "/intel/storage/ceph/mon/*/cluster/osd_bytes_avail", description: "Available space"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pool", description: "Pools"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg", description: "Placement groups"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg_active_clean", description: "Placement groups in active+clean state"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg_active", description: "Placement groups in active state"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_pg_peering", description: "Placement groups in peering state"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object", description: "Objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object_degraded", description: "Degraded (missing replicas) objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object_misplaced", description: "Misplaced (wrong location in the cluster) objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_object_unfound", description: "Unfound objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_bytes", description: "Size of all objects"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mds_up", description: "MDSs that are up"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mds_in", description: "MDS in state in (they are in cluster)"},
	{ns: "/intel/storage/ceph/mon/*/cluster/num_mds_failed", description: "Failed MDS"},
	{ns: "/intel/storage/ceph/mon/*/cluster/mds_epoch", description: "Current epoch of MDS map"},
	{ns: "/intel/storage/ceph/mon/*/finisher-monstore/queue_len", description: "Length of queue in finisher-monstore"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_transaction", description: "Transactions"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_get_latency", description: "Get Latency"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_submit_latency", description: "Submit Latency"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_submit_sync_latency", description: "Submit Sync Latency"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact", description: "Compactions"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact_range", description: "Compactions by range"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact_queue_merge", description: "Mergings of ranges in compaction queue"},
	{ns: "/intel/storage/ceph/mon/*/leveldb/leveldb_compact_queue_len", description: "Length of compaction queue"},
	{ns: "/intel/storage/ceph/mon/*/mon/num_sessions", description: "Open sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/session_add", description: "Created sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/session_rm", description: "Removed sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/session_trim", description: "Trimmed sessions"},
	{ns: "/intel/storage/ceph/mon/*/mon/num_elections", description: "Elections participated in"},
	{ns: "/intel/storage/ceph/mon/*/mon/election_call", description: "Elections started"},
	{ns: "/intel/storage/ceph/mon/*/mon/election_win", description: "Elections won"},
	{ns: "/intel/storage/ceph/mon/*/mon/election_lose", description: "Elections lost"},
	{ns: "/intel/storage/ceph/mon/*/paxos/start_leader", description: "Starts in leader role"},
	{ns: "/intel/storage/ceph/mon/*/paxos/start_peon", description: "Starts in peon role"},
	{ns: "/intel/storage/ceph/mon/*/paxos/restart", description: "Restarts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/refresh", description: "Refreshes"},
	{ns: "/intel/storage/ceph/mon/*/paxos/refresh_latency/avgcount", description: "Refresh latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/refresh_latency/sum", description: "Refresh latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin", description: "Started and handled begins"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_keys/avgcount", description: "Keys in transaction on begin"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_keys/sum", description: "Keys in transaction on begin"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_bytes/avgcount", description: "Data in transaction on begin"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_bytes/sum", description: "Data in transaction on begin"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_latency/avgcount", description: "Latency of begin operation"},
	{ns: "/intel/storage/ceph/mon/*/paxos/begin_latency/sum", description: "Latency of begin operation"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit", description: "Commits"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_keys/avgcount", description: "Keys in transaction on commit"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_keys/sum", description: "Keys in transaction on commit"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_bytes/avgcount", description: "Data in transaction on commit"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_bytes/sum", description: "Data in transaction on commit"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_latency/avgcount", description: "Commit latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/commit_latency/sum", description: "Commit latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect", description: "Peon collects"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_keys/avgcount", description: "Keys in transaction on peon collect"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_keys/sum", description: "Keys in transaction on peon collect"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_bytes/avgcount", description: "Data in transaction on peon collect"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_bytes/sum", description: "Data in transaction on peon collect"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_latency/avgcount", description: "Peon collect latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_latency/sum", description: "Peon collect latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_uncommitted", description: "Uncommitted values in started and handled collects"},
	{ns: "/intel/storage/ceph/mon/*/paxos/collect_timeout", description: "Collect timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/accept_timeout", description: "Accept timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/lease_ack_timeout", description: "Lease acknowledgement timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/lease_timeout", description: "Lease timeouts"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state", description: "Store a shared state on disk"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_keys/avgcount", description: "Keys in transaction in stored state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_keys/sum", description: "Keys in transaction in stored state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_bytes/avgcount", description: "Data in transaction in stored state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_bytes/sum", description: "Data in transaction in stored state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_latency/avgcount", description: "Storing state latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/store_state_latency/sum", description: "Storing state latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state", description: "Sharings of state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state_keys/avgcount", description: "Keys in shared state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state_keys/sum", description: "Keys in shared state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state_bytes/avgcount", description: "Data in shared state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/share_state_bytes/sum", description: "Data in shared state"},
	{ns: "/intel/storage/ceph/mon/*/paxos/new_pn", description: "New proposal number queries"},
	{ns: "/intel/storage/ceph/mon/*/paxos/new_pn_latency/avgcount", description: "New proposal number getting latency"},
	{ns: "/intel/storage/ceph/mon/*/paxos/new_pn_latency/sum", description: "New proposal number getting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_client_bytes/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-mon_daemon_bytes/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get", description: "Gets"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/take", description: "Takes"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/put", description: "Puts"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/mon/*/throttle-msgr_dispatch_throttler-mon/wait/sum", description: "Waiting latency"},

	// OSD
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/bytes_dirtied", description: "Dirty data"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/bytes_wb", description: "Written data"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/ios_dirtied", description: "Dirty operations"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/ios_wb", description: "Written operations"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/inodes_dirtied", description: "Entries waiting for write"},
	{ns: "/intel/storage/ceph/osd/*/WBThrottle/inodes_wb", description: "Written entries"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_queue_max_ops", description: "Max operations in journal queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_queue_ops", description: "Operations in journal queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_ops", description: "Total journal entries written"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_queue_max_bytes", description: "Max data in journal queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_queue_bytes", description: "Size of journal queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_bytes", description: "Total operations size in journal"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_latency/avgcount", description: "Average journal queue completing latency"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_latency/sum", description: "Average journal queue completing latency"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_wr", description: "Journal write IOs"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_wr_bytes/avgcount", description: "Journal data written"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_wr_bytes/sum", description: "Journal data written"},
	{ns: "/intel/storage/ceph/osd/*/filestore/journal_full", description: "Journal writes while full"},
	{ns: "/intel/storage/ceph/osd/*/filestore/committing", description: "Is currently committing"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle", description: "Commit cycles"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle_interval/avgcount", description: "Average interval between commits"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle_interval/sum", description: "Average interval between commits"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle_latency/avgcount", description: "Average latency of commit"},
	{ns: "/intel/storage/ceph/osd/*/filestore/commitcycle_latency/sum", description: "Average latency of commit"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_max_ops", description: "Max operations in writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_ops", description: "Operations in writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/ops", description: "Operations written to store"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_max_bytes", description: "Max data in writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/op_queue_bytes", description: "Size of writing to FS queue"},
	{ns: "/intel/storage/ceph/osd/*/filestore/bytes", description: "Data written to store"},
	{ns: "/intel/storage/ceph/osd/*/filestore/apply_latency/avgcount", description: "Apply latency"},
	{ns: "/intel/storage/ceph/osd/*/filestore/apply_latency/sum", description: "Apply latency"},
	{ns: "/intel/storage/ceph/osd/*/filestore/queue_transaction_latency_avg/avgcount", description: "Store operation queue latency"},
	{ns: "/intel/storage/ceph/osd/*/filestore/queue_transaction_latency_avg/sum", description: "Store operation queue latency"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_transaction", description: "Transactions"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_get_latency", description: "Get Latency"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_submit_latency", description: "Submit Latency"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_submit_sync_latency", description: "Submit Sync Latency"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact", description: "Compactions"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact_range", description: "Compactions by range"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact_queue_merge", description: "Mergings of ranges in compaction queue"},
	{ns: "/intel/storage/ceph/osd/*/leveldb/leveldb_compact_queue_len", description: "Length of compaction queue"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::completions_lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::completions_lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::finisher_lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::finisher_lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::write_lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::write_lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::writeq_lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-FileJournal::writeq_lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::ApplyManager::apply_lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::ApplyManager::apply_lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::ApplyManager::com_lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::ApplyManager::com_lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::SubmitManager::lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-JOS::SubmitManager::lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-WBThrottle::lock/wait/avgcount", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/mutex-WBThrottle::lock/wait/sum", description: "Average time of mutex in locked state"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_active", description: "Operations active"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_laggy", description: "Laggy operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_send", description: "Sent operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_send_bytes", description: "Sent data"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_resend", description: "Resent operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_ack", description: "Commit callbacks"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_commit", description: "Operation commits"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op", description: "Operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_r", description: "Read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_w", description: "Write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_rmw", description: "Read-modify-write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/op_pg", description: "PG operation"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_stat", description: "Stat operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_create", description: "Create object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_read", description: "Read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_write", description: "Write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_writefull", description: "Write full object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_append", description: "Append operation"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_zero", description: "Set object to zero operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_truncate", description: "Truncate object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_delete", description: "Delete object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_mapext", description: "Map extent operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_sparse_read", description: "Sparse read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_clonerange", description: "Clone range operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_getxattr", description: "Get xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_setxattr", description: "Set xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_cmpxattr", description: "Xattr comparison operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_rmxattr", description: "Remove xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_resetxattrs", description: "Reset xattr operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_tmap_up", description: "TMAP update operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_tmap_put", description: "TMAP put operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_tmap_get", description: "TMAP get operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_call", description: "Call (execute) operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_watch", description: "Watch by object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_notify", description: "Notify about object operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_src_cmpxattr", description: "Extended attribute comparison in multi operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_pgls", description: " [No description available]"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_pgls_filter", description: " [No description available]"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osdop_other", description: "Other operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_active", description: "Active lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_send", description: "Sent lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_resend", description: "Resent lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/linger_ping", description: "Sent pings to lingering operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolop_active", description: "Active pool operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolop_send", description: "Sent pool operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolop_resend", description: "Resent pool operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolstat_active", description: "Active get pool stat operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolstat_send", description: "Pool stat operations sent"},
	{ns: "/intel/storage/ceph/osd/*/objecter/poolstat_resend", description: "Resent pool stats"},
	{ns: "/intel/storage/ceph/osd/*/objecter/statfs_active", description: "Statfs operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/statfs_send", description: "Sent FS stats"},
	{ns: "/intel/storage/ceph/osd/*/objecter/statfs_resend", description: "Resent FS stats"},
	{ns: "/intel/storage/ceph/osd/*/objecter/command_active", description: "Active commands"},
	{ns: "/intel/storage/ceph/osd/*/objecter/command_send", description: "Sent commands"},
	{ns: "/intel/storage/ceph/osd/*/objecter/command_resend", description: "Resent commands"},
	{ns: "/intel/storage/ceph/osd/*/objecter/map_epoch", description: "OSD map epoch"},
	{ns: "/intel/storage/ceph/osd/*/objecter/map_full", description: "Full OSD maps received"},
	{ns: "/intel/storage/ceph/osd/*/objecter/map_inc", description: "Incremental OSD maps received"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_sessions", description: "Open sessions"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_session_open", description: "Sessions opened"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_session_close", description: "Sessions closed"},
	{ns: "/intel/storage/ceph/osd/*/objecter/osd_laggy", description: "Laggy OSD sessions"},
	{ns: "/intel/storage/ceph/osd/*/objecter/omap_wr", description: "OSD OMAP write operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/omap_rd", description: "OSD OMAP read operations"},
	{ns: "/intel/storage/ceph/osd/*/objecter/omap_del", description: "OSD OMAP delete operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_wip", description: "Replication operations currently being processed (primary)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op", description: "Client operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_in_bytes", description: "Client operations total write size"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_out_bytes", description: "Client operations total read size"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_latency/avgcount", description: "Latency of client operations (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_latency/sum", description: "Latency of client operations (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_process_latency/avgcount", description: "Latency of client operations (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_process_latency/sum", description: "Latency of client operations (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r", description: "Client read operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_out_bytes", description: "Client data read"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_latency/avgcount", description: "Latency of read operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_latency/sum", description: "Latency of read operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_process_latency/avgcount", description: "Latency of read operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_r_process_latency/sum", description: "Latency of read operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w", description: "Client write operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_in_bytes", description: "Client data written"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_rlat/avgcount", description: "Client write operation readable applied latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_rlat/sum", description: "Client write operation readable applied latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_latency/avgcount", description: "Latency of write operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_latency/sum", description: "Latency of write operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_process_latency/avgcount", description: "Latency of write operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_w_process_latency/sum", description: "Latency of write operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw", description: "Client read-modify-write operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_in_bytes", description: "Client read-modify-write operations write in"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_out_bytes", description: "Client read-modify-write operations read out"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_rlat/avgcount", description: "Client read-modify-write operation readable applied latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_rlat/sum", description: "Client read-modify-write operation readable applied latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_latency/avgcount", description: "Latency of read-modify-write operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_latency/sum", description: "Latency of read-modify-write operation (including queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_process_latency/avgcount", description: "Latency of read-modify-write operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_rw_process_latency/sum", description: "Latency of read-modify-write operation (excluding queue time)"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop", description: "Suboperations"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_in_bytes", description: "Suboperations total size"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_latency/avgcount", description: "Suboperations latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_latency/sum", description: "Suboperations latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_w", description: "Replicated writes"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_w_in_bytes", description: "Replicated written data size"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_w_latency/avgcount", description: "Replicated writes latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_w_latency/sum", description: "Replicated writes latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_pull", description: "Suboperations pull requests"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_pull_latency/avgcount", description: "Suboperations pull latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_pull_latency/sum", description: "Suboperations pull latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_push", description: "Suboperations push messages"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_push_in_bytes", description: "Suboperations pushed size"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_push_latency/avgcount", description: "Suboperations push latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/subop_push_latency/sum", description: "Suboperations push latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/pull", description: "Pull requests sent"},
	{ns: "/intel/storage/ceph/osd/*/osd/push", description: "Push messages sent"},
	{ns: "/intel/storage/ceph/osd/*/osd/push_out_bytes", description: "Pushed size"},
	{ns: "/intel/storage/ceph/osd/*/osd/push_in", description: "Inbound push messages"},
	{ns: "/intel/storage/ceph/osd/*/osd/push_in_bytes", description: "Inbound pushed size"},
	{ns: "/intel/storage/ceph/osd/*/osd/recovery_ops", description: "Started recovery operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/loadavg", description: "CPU load"},
	{ns: "/intel/storage/ceph/osd/*/osd/buffer_bytes", description: "Total allocated buffer size"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg", description: "Placement groups"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg_primary", description: "Placement groups for which this osd is primary"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg_replica", description: "Placement groups for which this osd is replica"},
	{ns: "/intel/storage/ceph/osd/*/osd/numpg_stray", description: "Placement groups ready to be deleted from this osd"},
	{ns: "/intel/storage/ceph/osd/*/osd/heartbeat_to_peers", description: "Heartbeat (ping) peers we send to"},
	{ns: "/intel/storage/ceph/osd/*/osd/heartbeat_from_peers", description: "Heartbeat (ping) peers we recv from"},
	{ns: "/intel/storage/ceph/osd/*/osd/map_messages", description: "OSD map messages"},
	{ns: "/intel/storage/ceph/osd/*/osd/map_message_epochs", description: "OSD map epochs"},
	{ns: "/intel/storage/ceph/osd/*/osd/map_message_epoch_dups", description: "OSD map duplicates"},
	{ns: "/intel/storage/ceph/osd/*/osd/messages_delayed_for_map", description: "Operations waiting for OSD map"},
	{ns: "/intel/storage/ceph/osd/*/osd/stat_bytes", description: "OSD size"},
	{ns: "/intel/storage/ceph/osd/*/osd/stat_bytes_used", description: "Used space"},
	{ns: "/intel/storage/ceph/osd/*/osd/stat_bytes_avail", description: "Available space"},
	{ns: "/intel/storage/ceph/osd/*/osd/copyfrom", description: "Rados \"copy-from\" operations"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_promote", description: "Tier promotions"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_flush", description: "Tier flushes"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_flush_fail", description: "Failed tier flushes"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_try_flush", description: "Tier flush attempts"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_try_flush_fail", description: "Failed tier flush attempts"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_evict", description: "Tier evictions"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_whiteout", description: "Tier whiteouts"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_dirty", description: "Dirty tier flag set"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_clean", description: "Dirty tier flag cleaned"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_delay", description: "Tier delays (agent waiting)"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_proxy_read", description: "Tier proxy reads"},
	{ns: "/intel/storage/ceph/osd/*/osd/tier_proxy_write", description: "Tier proxy writes"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_wake", description: "Tiering agent wake up"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_skip", description: "Objects skipped by agent"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_flush", description: "Tiering agent flushes"},
	{ns: "/intel/storage/ceph/osd/*/osd/agent_evict", description: "Tiering agent evictions"},
	{ns: "/intel/storage/ceph/osd/*/osd/object_ctx_cache_hit", description: "Object context cache hits"},
	{ns: "/intel/storage/ceph/osd/*/osd/object_ctx_cache_total", description: "Object context cache lookups"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_cache_hit"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_tier_flush_lat", description: "Object flush latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_tier_promote_lat", description: "Object promote latency"},
	{ns: "/intel/storage/ceph/osd/*/osd/op_tier_r_lat", description: "Object proxy read latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/initial_latency/avgcount", description: "Initial recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/initial_latency/sum", description: "Initial recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/started_latency/avgcount", description: "Started recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/started_latency/sum", description: "Started recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/reset_latency/avgcount", description: "Reset recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/reset_latency/sum", description: "Reset recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/start_latency/avgcount", description: "Start recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/start_latency/sum", description: "Start recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/primary_latency/avgcount", description: "Primary recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/primary_latency/sum", description: "Primary recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/peering_latency/avgcount", description: "Peering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/peering_latency/sum", description: "Peering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/backfilling_latency/avgcount", description: "Backfilling recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/backfilling_latency/sum", description: "Backfilling recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitremotebackfillreserved_latency/avgcount", description: "Wait remote backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitremotebackfillreserved_latency/sum", description: "Wait remote backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitlocalbackfillreserved_latency/avgcount", description: "Wait local backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitlocalbackfillreserved_latency/sum", description: "Wait local backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/notbackfilling_latency/avgcount", description: "Notbackfilling recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/notbackfilling_latency/sum", description: "Notbackfilling recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repnotrecovering_latency/avgcount", description: "Repnotrecovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repnotrecovering_latency/sum", description: "Repnotrecovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repwaitrecoveryreserved_latency/avgcount", description: "Rep wait recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repwaitrecoveryreserved_latency/sum", description: "Rep wait recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repwaitbackfillreserved_latency/avgcount", description: "Rep wait backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/repwaitbackfillreserved_latency/sum", description: "Rep wait backfill reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/RepRecovering_latency/avgcount", description: "RepRecovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/RepRecovering_latency/sum", description: "RepRecovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/activating_latency/avgcount", description: "Activating recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/activating_latency/sum", description: "Activating recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitlocalrecoveryreserved_latency/avgcount", description: "Wait local recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitlocalrecoveryreserved_latency/sum", description: "Wait local recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitremoterecoveryreserved_latency/avgcount", description: "Wait remote recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitremoterecoveryreserved_latency/sum", description: "Wait remote recovery reserved recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/recovering_latency/avgcount", description: "Recovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/recovering_latency/sum", description: "Recovering recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/recovered_latency/avgcount", description: "Recovered recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/recovered_latency/sum", description: "Recovered recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/clean_latency/avgcount", description: "Clean recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/clean_latency/sum", description: "Clean recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/active_latency/avgcount", description: "Active recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/active_latency/sum", description: "Active recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/replicaactive_latency/avgcount", description: "Replicaactive recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/replicaactive_latency/sum", description: "Replicaactive recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/stray_latency/avgcount", description: "Stray recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/stray_latency/sum", description: "Stray recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getinfo_latency/avgcount", description: "Getinfo recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getinfo_latency/sum", description: "Getinfo recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getlog_latency/avgcount", description: "Getlog recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getlog_latency/sum", description: "Getlog recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitactingchange_latency/avgcount", description: "Waitactingchange recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitactingchange_latency/sum", description: "Waitactingchange recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/incomplete_latency/avgcount", description: "Incomplete recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/incomplete_latency/sum", description: "Incomplete recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getmissing_latency/avgcount", description: "Getmissing recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/getmissing_latency/sum", description: "Getmissing recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitupthru_latency/avgcount", description: "Waitupthru recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/recoverystate_perf/waitupthru_latency/sum", description: "Waitupthru recovery state latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_bytes/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-filestore_ops/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_bytes/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-journal_ops/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-client/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-cluster/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_back_server/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hb_front_server/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-hbclient/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-msgr_dispatch_throttler-ms_objecter/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_bytes/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-objecter_ops/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_bytes/wait/sum", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/val", description: "Currently available throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/max", description: "Max value for throttle"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get", description: "Gets"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get_sum", description: "Got data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get_or_fail_fail", description: "Get blocked during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/get_or_fail_success", description: "Successful get during get_or_fail"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/take", description: "Takes"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/take_sum", description: "Taken data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/put", description: "Puts"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/put_sum", description: "Put data"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/wait/avgcount", description: "Waiting latency"},
	{ns: "/intel/storage/ceph/osd/*/throttle-osd_client_messages/wait/sum", description: "Waiting latency"},
}
